FROM jenkins/jenkins:lts-jdk17

USER root

# Paquetes básicos y sudo
RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    wget \
    git \
    ca-certificates \
    apt-transport-https \
    gnupg \
    lsb-release \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Crear usuario desarrollador con sudo sin password
RUN useradd -m -s /bin/bash desarrollador \
    && echo "desarrollador ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Instalar Docker CLI
RUN curl -fsSL https://get.docker.com | sh

# Dar acceso a Docker al usuario desarrollador y a jenkins
RUN usermod -aG docker desarrollador \
    && usermod -aG docker jenkins

# Instalar kubectl
RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/kubectl

# Instalar kind
RUN curl -Lo /usr/local/bin/kind "https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64" \
    && chmod +x /usr/local/bin/kind

# Instalar Helm por binario
RUN HELM_VERSION=$(curl -s https://api.github.com/repos/helm/helm/releases/latest \
      | grep tag_name | cut -d '"' -f4) \
    && curl -L "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz" -o /tmp/helm.tgz \
    && tar -xzf /tmp/helm.tgz -C /tmp \
    && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm \
    && rm -rf /tmp/helm.tgz /tmp/linux-amd64


# ArgoCD CLI (simple)
RUN curl -sSL -o argocd-linux-amd64 \
      https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 \
    && install -m 555 argocd-linux-amd64 /usr/local/bin/argocd \
    && rm argocd-linux-amd64

# -----------------------------
# Ajustar UID/GID de jenkins para que coincida con el host (UID 978)
# -----------------------------
RUN usermod --uid 978 jenkins \
    && groupmod --gid 976 jenkins \
    && chown -R jenkins:jenkins /var/jenkins_home /usr/share/jenkins/ref

# Volumen para Jenkins (persistencia)
VOLUME ["/var/jenkins_home"]

# Exponer puertos de Jenkins
EXPOSE 8080 50000

# Usuario por defecto para entrar al contenedor (puedes cambiar a jenkins si prefieres)
USER desarrollador

CMD ["/bin/bash"]
