version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfile-infra
    container_name: jenkins
    restart: unless-stopped
    user: "1004:1005"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock           # Permite usar Docker desde Jenkins
      - /home/desarrollador/proyecto_tokio/techwave_web_K8s/argoCD:/var/jenkins_home
      
