name: Build and Deploy Docker Image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
    paths-ignore:
      - helm/flask-app/values-green.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Debug event
        run: |
          echo "EVENT: $GITHUB_EVENT_NAME"
          echo "REF: $GITHUB_REF"

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
            echo "Release detected: $IMAGE_TAG"
          else
            IMAGE_TAG=${GITHUB_SHA::8}
            echo "CI build detected: $IMAGE_TAG"
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t lumuma2025/techwave_web_k8s:$IMAGE_TAG -f docker/Dockerfile .

      - name: Push Docker image
        run: |
          docker push lumuma2025/techwave_web_k8s:$IMAGE_TAG

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update Helm values.yaml
        run: |
          yq -i '.image.tag = strenv(IMAGE_TAG)' helm/flask-app/values-green.yaml

      - name: Debug values file
        run: cat helm/flask-app/values-green.yaml

      - name: Commit and push updated values.yaml
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "luismuma"
          git config user.email "luismuma@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/luismuma/techwave_web_K8s.git

          git add helm/flask-app/values-green.yaml
          git commit -m "chore: update image tag to ${IMAGE_TAG} [ci skip]" || exit 0

          # 🔥 Traer la última versión de main
          git fetch origin main
      
          # 🔥 Si NO estamos en main, cambiamos a main
          git checkout main || git checkout -b main origin/main
      
          # 🔥 Rebase para evitar non-fast-forward
          git rebase origin/main
      
          # 🔥 Aplicar el commit que hiciste antes (si existe)
          git cherry-pick HEAD@{1} || true
      
          # 🔥 Push limpio
          git push origin main
