name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar código
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
       # 1. configurar AWS credential
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Login a Docker Hub
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construir imagen con tag dinámico (SHA corto)
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t lumuma2025/techwave_web_k8s:$IMAGE_TAG -f docker/Dockerfile .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 4. Push de la imagen al Docker Hub
      - name: Push Docker image
        run: |
          docker push lumuma2025/techwave_web_k8s:$IMAGE_TAG

      # 5. Actualizar Helm values.yaml con la nueva versión
      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"$IMAGE_TAG\"|" $GITHUB_WORKSPACE/helm/flask-app/values.yaml

      # 6. Commit y push
      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          git add helm/flask-app/values.yaml
          git commit -m "chore: update Docker image to $IMAGE_TAG" || echo "No changes to commit"
          git push

      # 7. Verificar imagen construida (opcional)
      - name: Verify Docker image
        run: docker images
